version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.cucumber:cucumber-java
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.9.1
  - dependency-name: io.cucumber:cucumber-junit
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.9.1
  - dependency-name: org.testng:testng
    versions:
    - 7.3.0
