tools:
  jdk:
    - 8
  maven:
    - 3.3.9
  sonarscanner:
    - 3.0.3.778

triggers:
  push: enabled
    ignoreMessage: \[ignore\] .*
  pr: enabled

flows:
  runsonar:
    - sonar("Sonar"):
       - (name sonar) mvn -e -V -B -fae sonar:sonar

  versionsCheck:
    - (name JDK Version) java -version
    - (name Maven version) mvn -v

  build:
   - exposeVars(maven)
   - (name Maven deploy) mvn -B clean test
   - call: runsonar
     
  hygieiaPublish:
     - hygieia.publishBuild()

  default:
       try:
          - call: versionsCheck
          - call: build
       finally:
          - call: hygieiaPublish

  pr:
   - call: default
