tools:
  jdk: 8
  maven: 3.5.0

envs:
  global:
    variables:
      date: "19th of October"
      adjective: "rainy"
  summer:
    variables: 
      date: "18th of August"
      adjective: "hot and sunny"


flows:
  default:
    - call: start
    - call: start(summer)
    - call: versions
  
  start:
    - shell(name Start): echo "Hello everyone on this ${adjective} ${date}."

  versions:
    - shell(name Java check):  java -version
    - shell(name Maven check): mvn -v
    - shell(name Ruby check):  ruby -v