tools:
  jdk: 8
  maven: 3.5.0

flows:
  default:
  - node(osx):
    - shell: echo "Hello everyone on this rainy 19th of October!"
    - shell: java -version
    - shell: mvn -v
    - shell: ruby -v