tools:
  jdk: 8
  maven: 3.5.0

flows:
  default:
#  - node(osx):
    - shell(name Start): echo "Hello everyone on this rainy 19th of October!"
    - java -version
    - (name Maven check) mvn -v
    - shell(name Ruby check): ruby -v